project:
  type: website
  #output-dir: docs

website:
  title: "SDA1"
  navbar:
    logo: /misc/SU_logotyp_Staende_800px.png
    background: primary
    left:
      - href: index.qmd
        text: Översikt
      - href: DelA.qmd
        text: Dataanalys, 7.5 hp
      - href: DelB.qmd
        text: Statistiska modeller och inferens, 7.5 hp
      - href: R.qmd
        text: R
format:
  html:
    theme: superhero # litera, lumen, superhero, united
    css: styles.css
    toc: true
    #monobackgroundcolor: #c3d0e6
callout-appearance: simple




