---
title: "Del I - Dataanalys och Regression, 7.5 hp"
format: html
---

> I momentet ingår insamling, bearbetning, visualisering och sammanfattning av data i programspråket R. En stor del av momentet behandlar sambands- och regressionsanalys som utmynnar i metoder för prediktion.

Förkortningen **SDM** står för kursboken [Stats: Data and Models](https://nordics.pearson.com/products/stats-data-and-models-5th-global-edition-e-book?variant=42945920630933) 5:e upplagan, global edition.

Under vissa föreläsningar länkar vi till `Extramaterial`. Det är material som inte krävs för att klara kursen, men som den nyfikne kan läsa för att få en djupare förståelse.

### **Föreläsningar**

**Föreläsning 1 - Introduktion.**\
Läs: SDM Kapitel 1 | [Slides](/slides/F1Intro.pdf) 

**Föreläsning 2 - Kort introduktion till R. **\
Läs: [Slides](/slides/F2.pdf)\
Kod: [Kod](/slides/code/R_lecture_examples.R)\
Data: [SmartPhones](/datorlab/lab3/SmartPhones.RData) | [CAPM](/datorlab/lab3/CAPM_data.RData)

**Föreläsning 3 - Hantera och beskriva data.**\
Läs: SDM Kapitel 2 | [Slides](/slides/F3.pdf)\
Interaktivt: [widget - histogram](/observable/histogram.qmd)

**Föreläsning 4 - Samband mellan kategoriska variabler.**\
Läs: SDM Kapitel 3 | [Slides](/slides/F4.pdf) 

**Föreläsning 5 - Jämföra fördelningar. Tidsserier. Transformationer.**\
Läs: SDM Kapitel 4 | [Slides](/slides/F5.pdf) 

**Föreläsning 6 - Standardisering och normalmodellen.**\
Läs: SDM Kapitel 5 | [Slides](/slides/F6.pdf) 

**Föreläsning 7 - Samband mellan numeriska variabler.**\
Läs: SDM Kapitel 6 | [Slides](/misc/larry.png) 

**Föreläsning 8 - Enkel linjär regression.**\
Läs: SDM Kapitel 7 | [Slides](/misc/larry.png)\
[widget - linjär regression utan population](/observable/linreg_simple_estimates.qmd) | [widget - linjär regression med population](/observable/linreg_simple.qmd)

**Föreläsning 9 - Multipel linjär regression.**\
Läs: SDM Kapitel 8-9 | [Slides](/misc/larry.png)\
Extramaterial: [widget - icke-linjär regression](/observable/ickelinregression.qmd)

**Föreläsning 10 - Populationer och stickprov. Undersökningar och experiment.**\
Läs: SDM 10.1-10.3 och 11.1-11.2 | [Slides](/misc/larry.png) 

**Föreläsning 11 - Sammanfattning**\
Läs: [Slides](/misc/larry.png) 

### **Räkneövningar**

Övningarna i kursboken [Stats: Data and Models (SDM)](https://nordics.pearson.com/products/stats-data-and-models-5th-global-edition-e-book?variant=42945920630933) hänvisas till med kapitelnummer följt av övningsnummer.

**Övning 1 - Beskrivande statistik.**\
Uppgifter: SDM 2.1, 2.2, 2.6, 2.7, 2.9, 2.11, 2.12, 2.14, 2.15, 2.16, 2.17, 2.20, 2.21, 2.24. 

**Övning 2 - Samband mellan kategoriska variabler. Transformationer.**\
Uppgifter:  SDM 3.1, 3.3, 3.5, 3.6, 3.7, 3.9, 3.25, 3.31, 3.39, 3.41, 3.47, 4.1, 4.3, 4.14, 4.17, 4.45.

**Övning 3 - Standarisering och normalmodellen.**\
Uppgifter: SDM 5.1, 5.2, 5.4, 5.5, 5.8, 5.10, 5.14, 5.16, 5.17, 5.30, 5.42, 5.48.

**Övning 4 - Samband mellan numeriska variabler. Korrelation och enkel linjär regression.**\
Uppgifter:  SDM 6.2,  6.3, 6.5, 6.6, 6.9, 6.14, 6.20, 7.1, 7.2, 7.3, 7.4, 7.5, 7.7, 7.9, 7.11, 7.13, 7.15, 7.19, 7.23, 7.27, 7.52.

**Övning 5 - Multipel linjär regression.**\
Uppgifter: SDM Kapitel 8.18, 8.20, 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.9, 9.11, 9.14, 9.16, 9.22, 9.23, 9.28.

**Övning 6 - Populationer och stickprov. Undersökningar och experiment.**\
Uppgifter: Meddelas snart 

### **Datorlaborationer**

**Datorlaboration 1 - Introduktion till R.**\
Uppgifter: [html](/datorlab/lab1/DatorLab1.qmd)

**Datorlaboration 2 - Beskrivande statistik och visualisering i R.**\
Uppgifter: [html](/datorlab/lab2/DatorLab2.qmd) | <a href="https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab2/DatorLab2.qmd" download>quarto</a> 

**Datorlaboration 3 - Samband mellan två kategoriska variabler. Samband mellan en kategorisk och en numerisk variabel. Tidsserier.**\
Uppgifter: [html](/datorlab/lab3/DatorLab3.qmd) | <a href="https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab3/DatorLab3.qmd" download>quarto</a> 

**Datorlaboration 4 - Korrelation. Enkel och multipel linjär samt icke-linjär regression.**\
Uppgifter: [html](/datorlab/lab4/DatorLab4.qmd) | <a href="https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab4/DatorLab4.qmd" download>quarto</a>

### **Inlämningsuppgift**

**Inlämningsuppgift 1.**\
Uppgifter: [html](/assignments/assignment1/Assignment1.qmd) | <a href="https://github.com/StatisticsSU/SDA1/raw/main/assignments/assignment1/Assignment1.qmd" download>quarto</a> 
