---
title: "Del II - Sannolikhetsmodeller och Inferens, 7.5 hp"
format: html
---

> I kursens andra momentet behandlas inledningsvis sannolikheter, slumpvariabler och sannolikhetsfördelningar. En central del i momentet är inferens, dvs. statistiska metoder för att dra slutsatser om olika fenomen från data, bl a samband från regressionsanalys. Kursen avslutas med en introduktion till beslutsfattade under osäkerhet.

Förkortningen **SDM** står för kursboken [Stats: Data and Models](https://nordics.pearson.com/products/stats-data-and-models-5th-global-edition-e-book?variant=42945920630933) 5:e upplagan, global edition.

Under vissa föreläsningar länkar vi till `Extramaterial`. Det är material som inte krävs för att klara kursen, men som den nyfikne kan läsa för att få en djupare förståelse.

### **Föreläsningar**

**Föreläsning 12 - Osäkerhet och Sannolikhet.**\
Läs: SDM Kapitel 12 och 13 \| [Slides](/slides/F12Sannolikhet.pdf)\
Interaktivt: [slantsingling](/observable/storatalenslag_bernoulli.qmd)\
Extramaterial: [TedTalk om sannolikheter](https://youtu.be/0m5bg2hpHNw)

**Föreläsning 13 - Betingade sannolikheter och Bayes sats.**\
Läs: SDM Kapitel 13 \| [Slides](/slides/F13BetingadeSlhBayesSats.pdf)\
Interaktivt: [bayessats](/observable/bayestheorem.qmd)\
Extramaterial: [artikel om Bayes sats och snabbtest för Covid-19](https://www.varsity.co.uk/science/21149)

**Föreläsning 14 - Slumpvariabler och deras egenskaper.**\
Läs: SDM Kapitel 14 \| [Slides](/slides/F14Slumpvariabler.pdf)\
Interaktivt: [normalfördelningen](/observable/normalfordelningen.qmd)

**Föreläsning 15 - Sannolikhetsmodeller I**\
Läs: SDM Kapitel 15.1, 15.2, 15.3, 15.6 \| [Slides](/slides/F15Sannolikhetsmodeller1.pdf)\
Interaktivt: [bernoullifördelning](/observable/bernoullifordelningen.qmd) | [geometrisk fördelning](/observable/geometriskfordelning.qmd) | [binomialfördelningen](/observable/binomialfordelningen.qmd) | [likformig](/observable/uniformfordelning.qmd) | [normalfördelning](/observable/normalfordelningen.qmd)\
Kod: [geometric.R](/code/geometric.R)

**Föreläsning 16 - Sannolikhetsmodeller II**\
Läs: SDM Kapitel 5.3, 14.4, 15.7 \| [Slides](/slides/F16Sannolikhetsmodeller2.pdf)\
Interaktivt: [Poissonfördelningen](/observable/poissonfordelningen.qmd) \| [maximum likelihood - Poisson](/observable/ml_poisson.qmd) \| [exponential](/observable/exponentialfordelningen.qmd) \| [student-t](/observable/studentt.qmd) \| [allmän student-t](/observable/studentt_allman.qmd)\
Kod: [exponential.R](/code/exponential.R)\
Extramaterial: [Notebook - maximum likelihood för Poisson](https://observablehq.com/@mattiasvillani/maximum-likelihood-poissonmodellen) | [Notebook - student-t](https://observablehq.com/@mattiasvillani/student-t) 

**Föreläsning 17 - Samplingfördelningar och konfidensintervall för en andel.**\
Läs: SDM Kapitel 16.1-16.5 | [Slides](/slides/F17KI4prop.pdf)\
Interaktivt: [samplingfördelning - liten ändlig population](/observable/sampling_finite_pop.qmd) | [stora talens lag - normalapproximation för en andel](/observable/storatalenslag_bernoulli_normalapprox.qmd) | [samplingfördelning för andel - ändlig population](/observable/sampling_prop_finite_pop.qmd) | [konfidensintervall för en andel](/observable/konfidensintervall_andel.qmd)

**Föreläsning 18 - Konfidensintervall för ett väntevärde. Stora talens lag. Centrala gränsvärdessatsen.**\
Läs: SDM Kapitel 17 \| [Slides](/slides/F18KI4mean.pdf)\
Interaktivt: [stora talens lag](/observable/storatalenslag.qmd) | [centrala gränsvärdessatsen](/observable/cgs.qmd)\
Extramaterial: [Notebook - stora talens lag](https://observablehq.com/@mattiasvillani/stora-talens-lag) \| [Notebook - centrala gränsvärdessatsen](https://observablehq.com/@mattiasvillani/cgs)\
Kod: [confidence_intervals_salmon.R](/code/confidence_intervals_salmon.R)

**Föreläsning 19 - Hypotestest.**\
Läs: SDM Kapitel 18 (ej *Random matters* på sid 579) \| [Slides](/slides/F19HypotesTest.pdf)\
Interaktivt: [hypotestest - väntevärde](/observable/hypotestest_mean.qmd)

**Föreläsning 20 - Inferens i linjär regression - populationsmodell och samplingfördelning**\
Läs: SDM Kapitel 23.1-23.3 \| [Slides](/slides/F20Regression1.pdf)\
Kod: [regression lifespan data](/code/lifespan_regression.R)\
Interaktivt: [samplingfördelning regression](/observable/linreg_simple_sampling_dist.qmd)\
Extramaterial: [kod för residualanalys på simulerad regressionsdata](code/residualanalys_simulerade_data.R)

**Föreläsning 21 - Inferens i linjär regression - konfidensintervall, hypotestest och prediktionsintervall**\
Läs: SDM Kapitel 23.3-23.6 \| [Slides](/slides/F21Regression2.pdf)\

**Föreläsning 22 - Hypotestest och jämföra grupper.**\
Läs: SDM Kapitel 19, 20.4-20.5, 21.1-21.3 | [Slides](/slides/F22ComparePop.pdf)\
Interaktivt: [hypotestest fel typ I och II](/observable/hypotestest_typ1och2.qmd)

**Föreläsning 23 - $\chi^2$ goodness-of-fit test. Optimala beslut under osäkerhet.**\
Läs: SDM 22.1 | [Slides](/misc/larry.png)\
Interaktivt: [chi2-fördelningen](/observable/chi2fordelningen.qmd)

**Föreläsning 24 - Räkning av övningstenta.**\
Läs: [Slides](/misc/larry.png)

**Videoföreläsning - Maximum likelihood och Bayesiansk inferens.**\
Läs: [Slides](/misc/larry.png)\
Interaktivt: [maximum likelihood - Poisson](/observable/ml_poisson.qmd) | [betafördelningen](/observable/betafordelningen.qmd)\
Extramaterial: [notebook - matematisk härledning av maximum likelihood skattningen i Poissonmodellen](https://observablehq.com/@mattiasvillani/maximum-likelihood-poissonmodellen)


### **Räkneövningar**

Övningarna i kursboken [Stats: Data and Models (SDM)](https://nordics.pearson.com/products/stats-data-and-models-5th-global-edition-e-book?variant=42945920630933) hänvisas till med kapitelnummer följt av övningsnummer.

**Övning 7 - Sannolikheter för händelser. Kombinatorik.**\
Uppgifter: SDM 12.2, 12.5, 12.7, 12.9, 12.12, 12.16, 12.21, 12.27, 12.29, 12.31, 12.34, 12.36, 12.39, 12.41, 12.49, 12.52.

**Övning 8 - Oberoende händelser. Betingning och Bayes sats.**\
Uppgifter: SDM 13.1, 13.5, 13.7, 13.10, 13.12, 13.14, 13.18, 13.21, 13.24, 13.31, 13.47, 13.49.

**Övning 9 - Slumpvariabler, väntevärde och standardavvikelse.**\
Uppgifter: SDM 14.1, 14.3, 14.9a, 14.11, 14.13, 14.21, 14.26, 14.33, 14.36, 14.43, 14.54.

**Övning 10 - Sannolikhetsmodeller I.**\
Uppgifter: SDM 15.1, 15.3, 15.5, 15.18, 15.19, 15.21, 15.28, 15.29, 15.31, 15.41, 15.45.

**Övning 11 - Sannolikhetsmodeller II.**\
Uppgifter: SDM 15.7, 15.11, 15.12, 15.49, 15.59, 15.60, 15.61, 15.62.

**Övning 12 - Konfidensintervall.**\
Uppgifter: SDM 16.2, 16.3, 16.5, 16.7, 16.14, 16.16, 16.27a-c), 16.31, 17.23, 17.29, 17.31, 17.56.

**Övning 13 - Hypotestest.**\
Uppgifter: SDM 18.1, 18.4, 18.5, 18.8, 18.10, 18.14, 18.16, 18.23, 18.27, 18.45, 18.50.

**Övning 14 - Inferens för regression.**\
Uppgifter: SDM 23.1, 23.3, 23.5, 23.7, 23.9, 23.13, 23.15, 23.17.

**Övning 15 - Jämföra grupper och chi2-test.**\
Uppgifter: SDM 20.11, 20.13, 20.15, 20.62, 21.19, 21.21.

### **Datorlaborationer**

**Datorlaboration 5 - Räkna med fördelningar i R. Simulering.**\
Uppgifter: [html](/datorlab/lab5/DatorLab5.qmd) | <a href="https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab5/DatorLab5.qmd" download>quarto</a>

**Datorlaboration 6 - Konfidensintervall, hypotesttest och centrala gränsvärdessatsen.**\
Uppgifter: [html](/datorlab/lab6/DatorLab6.qmd) | <a href="https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab6/DatorLab6.qmd" download>quarto</a>

**Datorlaboration 7 - Multipel linjär regression - inferens.**\
Uppgifter: [html](/datorlab/lab7/DatorLab7.qmd) | <a href="https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab7/DatorLab7.qmd" download>quarto</a>

### **Inlämningsuppgift**

**Inlämningsuppgift 2.**\
Uppgifter: [instruktioner i html](/assignments/assignment2/Assignment2instructions.qmd) | <a href="https://github.com/StatisticsSU/SDA1/raw/main/assignments/assignment2/Assignment2handin.qmd" download>quarto för inlämning</a> 


