---
title: "Dataanalys, 7.5 hp"
---

> I det här momentet ingår insamling, bearbetning, visualisering och sammanfattning av data i programspråket R. En stor del av momentet behandlar sambands- och regressionsanalys som utmynnar i metoder för prediktion.

### **Föreläsningar**

**Föreläsning 1 - Introduktion.**\
Läs: SDM Kapitel 1 | [Slides](/slides/SDA1_L1.html) 

**Föreläsning 2 - Introduktion till R. **\
Läs: LITTERATUR | [Slides](/misc/larry.png) 

**Föreläsning 3 - Hantera och beskriva data.**\
Läs: SDM Kapitel 2 | [Slides](/misc/larry.png) 

**Föreläsning 4 - Samband mellan kategoriska variabler.**\
Läs: SDM Kapitel 3 | [Slides](/misc/larry.png) 

**Föreläsning 5 - Jämföra fördelningar. Tidsserier. Transformationer.**\
Läs: SDM Kapitel 4 | [Slides](/misc/larry.png) 

**Föreläsning 6 - Standardisering och Normalmodellen.**\
Läs: SDM Kapitel 5 | [Slides](/misc/larry.png) 

**Föreläsning 7 - Samband mellan kontinuerliga variabler. Korrelation.**\
Läs: SDM Kapitel 6 | [Slides](/misc/larry.png) 

**Föreläsning 8 - Enkel linjär regression.**\
Läs: SDM Kapitel 7 | [Slides](/misc/larry.png)

**Föreläsning 9 - Multipel regression.**\
Läs: SDM Kapitel 9 | [Slides](/misc/larry.png) 

**Föreläsning 10 - Populationer och stickprov. Undersökningar och experiment.**\
Läs: SDM 10.1-10.3 och 11.1-11.2 | [Slides](/misc/larry.png) 

**Föreläsning 11 - Sammanfattning**\
Läs: [Slides](/misc/larry.png) 

**Videoföreläsning - Matematikrepetition.**\
Läs: [Slides](/misc/larry.png) 

### **Övningar**

**Övning 1 - Beskrivande statistik.**\
Uppgifter: SDM 2 

**Övning 2 - Samband mellan kategoriska variabler och korstabeller.**\
Uppgifter: SDM 3

**Övning 3 - Standardavvikelse och standardisering. Normalmodellen.**\
Uppgifter: SDM 5 

**Övning 4 - Korrelation.**\
Uppgifter: SDM 6 

**Övning 5 - Estimering och tolkning av enkel linjär regression.**\
Uppgifter: SDM 7

**Övning 6 - Prediktion med enkel linjär regression.**\
Uppgifter: SDM 7-9 

### **Datorlaborationer**

**Datorlaboration 1 - Intro till R**\
Uppgifter: [html](/datorlab/lab1/DatorLab1.html) eller [pdf](/datorlab/lab1/DatorLab1.pdf) | [Intro till Quarto rapportskrivning](/tutorials/Quarto/Intro2Quarto.html)

**Datorlaboration 2 - Beskrivande statistik och visualisering i R**\
Uppgifter: [Datorlab 2](/misc/larry.png) 

**Datorlaboration 3 - Korrelation och enkel linjär regression**\
Uppgifter: [Datorlab 3](/misc/larry.png) 

**Datorlaboration 4 - Multipel linjär regression**\
Uppgifter: [Datorlab 4](/misc/larry.png)
