---
title: "Del B - Sannolikheter och statistisk inferens"
---

### **Föreläsningar**

**Föreläsning 12 - Sannolikheter och sannolikhetsmodeller.**\
Läs: SDM Kapitel 12 och 13 | [Slides](/misc/larry.png) 

**Föreläsning 13 - Sannolikhetsberäkningar.**\
Läs: SDM Kapitel 13 | [Slides](/misc/larry.png)

**Föreläsning 14 - Slumpvariabler. Väntevärde. Varians. Linjärkombinationer.**\
Läs: SDM Kapitel 14 | [Slides](/misc/larry.png) 

**Föreläsning 15 - Diskreta sannolikhetsmodeller.**\
Läs: SDM Kapitel 15.1, 15.2, 15.3, 15.6 | [Slides](/misc/larry.png) 

**Föreläsning 16 - Kontinuerliga sannolikhetsmodeller.**\
Läs: SDM Kapitel 5.3, 15.7 | [Slides](/misc/larry.png) 

**Föreläsning 17 - Samplingfördelningar och konfidensintervall för en andel.**\
Läs: SDM Kapitel 16 | [Slides](/misc/larry.png) 

**Föreläsning 18 - Konfidensintervall för ett väntevärde. Stora talens lag. Centrala gränsvärdessatsen.**\
Läs: SDM Kapitel 17 | [Slides](/misc/larry.png) 

**Föreläsning 19 - Hypotestest.**\
Läs: SDM Kapitel 18 | [Slides](/misc/larry.png) 

**Föreläsning 20 - Hypotestest och jämföra grupper.**\
Läs: SDM Kapitel 19, 20.4, 20.5 | [Slides](/misc/larry.png) 

**Föreläsning 21 - Jämföra grupper och chi-2 test.**\
Läs: SDM Kapitel 21.1, 21.2 | [Slides](/misc/larry.png) 

**Föreläsning 22 - Inferens i multipel regression.**\
Läs: SDM Kapitel 23 | [Slides](/misc/larry.png) 

**Videoföreläsning - Maximum likelihood och Bayesiansk inferens.**\
Läs: Kompendium avsnitt X | [Slides](/misc/larry.png) 

**Föreläsning 23 - Sammanfattning.**\
Läs: [Slides](/misc/larry.png) 

### **Övningar**

**Övning 4 - Sannolikheter för händelser**\
Uppgifter: SDM 1.1-1.6, osv 

**Övning 5 - Kombinatorik, Oberoende händelser**\
Uppgifter: SDM 1.1-1.6, osv 

**Övning 6 - Betingning och Bayes sats**\
Uppgifter: SDM 1.1-1.6, osv 

**Övning 7**\
Uppgifter: SDM 1.1-1.6, osv 

**Övning 8**\
Uppgifter: SDM 1.1-1.6, osv 

**Övning 9**\
Uppgifter: SDM 1.1-1.6, osv 

**Övning 10**\
Uppgifter: SDM 1.1-1.6, osv 

**Övning 11**\
Uppgifter: SDM 1.1-1.6, osv 

**Övning 12**\
Uppgifter: SDM 1.1-1.6, osv 

**Övning 13**\
Uppgifter: SDM 1.1-1.6, osv 

**Övning 14**\
Uppgifter: SDM 1.1-1.6, osv 

### **Datorlaborationer**

**Datorlaboration 5 - Simulering från sannolikhetsfördelningar**\
Uppgifter: [Datorlab 5](/misc/larry.png) 

**Datorlaboration 6 - Samplingfördelningar, standardfel och konfidensintervall**\
Uppgifter: [Datorlab 6](/misc/larry.png) 

**Datorlaboration 7 - Multipel linjär regression**\
Uppgifter: [Datorlab 7](/misc/larry.png) 

**Datorlaboration 8 - Multipel linjär regression, forts**\
Uppgifter: [Datorlab 8](/misc/larry.png)
