---
title: "Interaktivt lärande"
format: 
  html:
    self-contained: true
toc: true
---

Här samlar vi alla interaktiva grafer (widgets) som vi länkar till från slides.<br>

Extramaterial: till varje interaktiv graf finns en interaktiv/reaktiv notebook med mer information, här finns en [lista med alla notebooks](https://observablehq.com/collection/@mattiasvillani/sda1). Dessa notebook ingår *inte* i kursen, men länkas här för den nyfikne studenten som vill läsa lite mer för en djupare förståelse.

## Del 1 - Dataanalys och Regression

### Föreläsning 3

**Val av antal bins i histogram**: <br>
[widget](/observable/histogram.qmd) | [notebook](https://observablehq.com/@mattiasvillani/histogram)

### Föreläsning 8

**Enkel linjär regression** <br>
[widget - utan population](/observable/linreg_simple_estimates.qmd)\
[widget - med population](/observable/linreg_simple.qmd) | [notebook](https://observablehq.com/@mattiasvillani/samplingfordelningen-linear-regression)

### Föreläsning 9

**Icke-linjär regression**: <br>
[widget](/observable/ickelinregression.qmd) | [notebook](https://observablehq.com/@mattiasvillani/icke-linjar-regression)


## Del 2 - Sannolikhetsmodeller och Inferens

### Föreläsning 12 

**Slantsingling och stora talens lag**<br>
[slantsingling - widget](/observable/storatalenslag_bernoulli.qmd) | [slantsingling - notebook](https://observablehq.com/@mattiasvillani/stora-talens-slantsingling)

### Föreläsning 13 

**Bayes sats**: <br>
[widget](/observable/bayestheorem.qmd) | [notebook](https://observablehq.com/@mattiasvillani/bayes-theorem-for-events)

### Föreläsning 14

**Normalfördelningen** <br>
[widget](/observable/normalfordelningen.qmd) | [notebook](https://observablehq.com/@mattiasvillani/normalfordelningen)

### Föreläsning 15 

**Bernoullifördelning** <br>
[widget](/observable/bernoullifordelningen.qmd)

**geometrisk fördelning** <br>
[widget](/observable/geometriskfordelning.qmd)

**binomialfördelning**: <br>
[widget](/observable/binomialfordelningen.qmd)

**Poissonfördelning** <br>
[widget](/observable/poissonfordelningen.qmd)

**Maximum likelihoodskattning - Poissonfördelning**: <br>
[widget](/observable/ml_poisson.qmd)

### Föreläsning 16

**likformig fördelning**: <br>
[widget](/observable/uniformfordelning.qmd) | [notebook](https://observablehq.com/@mattiasvillani/likformig-fordelningen)

**exponentialfördelning**: <br>
[widget](/observable/exponentialfordelningen.qmd) | [notebook](https://observablehq.com/@mattiasvillani/exponentialfordelningen)

**Student-*t* fördelning**: <br>
[widget](/observable/studentt.qmd) | [notebook](https://observablehq.com/@mattiasvillani/student-t)

**Allmän student-*t* fördelning**: <br>
[widget](/observable/studentt_allman.qmd) | [notebook](https://observablehq.com/@mattiasvillani/student-t-fordelning-allman-version)

### Föreläsning 17

**Samplingfördelning - ändlig population**<br>
[widget](/observable/sampling_finite_pop.qmd) | [notebook](https://observablehq.com/@mattiasvillani/samplingfordeling-for-andlig-population)

**Samplingfördelning för en andel - ändlig population**<br>
[widget](/observable/sampling_prop_finite_pop.qmd) | [notebook](https://observablehq.com/@mattiasvillani/samplingfordelning-for-andel-andlig_pop)

**Stora talens lag - normalapproximation av en andel**<br>
[widget](/observable/storatalenslag_bernoulli_normalapprox.qmd)

**Konfidensintervall för en andel - normalapproximation**<br>
[widget](/observable/konfidensintervall_andel.qmd)

### Föreläsning 18

**Stora talens lag**: <br>
[normalpopulation - widget](/observable/storatalenslag.qmd) | [normalpopulation - notebook](https://observablehq.com/@mattiasvillani/stora-talens-lag-allman)

**Centrala gränsvärdessatsen**: <br>
[widget](/observable/cgs.qmd) | [notebook](https://observablehq.com/@mattiasvillani/cgs)

**Samplingfördelning för ett medelvärde**<br>
[widget](/observable/sampling_mean_finite_pop.qmd) | [notebook](https://observablehq.com/@mattiasvillani/samplingfordelning-for-ett-medelvarde-andlig-population)


### Föreläsning 19

**Hypotesttest väntevärde**<br>
[widget](/observable/hypotestest_mean.qmd) 

### Föreläsning 20

**samplingfördelning regression** <br>
[widget](/observable/linreg_simple_samping_dist.qmd) | [notebook](https://observablehq.com/@mattiasvillani/samplingfordelningen-linear-regression)

### Föreläsning 21

**Hypotestest - fel av typ I och II**: <br>
[widget](/observable/hypotestest_typ1och2.qmd) | [notebook](https://observablehq.com/@mattiasvillani/typ1och2fel)

### Föreläsning 22

**Chi2-fördelning**: <br>
[widget](/observable/chi2fordelningen.qmd) | [notebook](https://observablehq.com/@mattiasvillani/chi2-fordelningen)


### Videoföreläsning

**Beta-fördelning**: <br>
[widget](/observable/betafordelningen.qmd)
