<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.256">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mattias Villani">
<meta name="dcterms.date" content="2023-03-03">

<title>SDA1 - Statistik och dataanalys I, 15 hp</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../..//misc/favicons/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  
  <script>
    (function () {
      var script = document.createElement("script");
      script.type = "text/javascript";
      script.src  = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js";
      document.getElementsByTagName("head")[0].appendChild(script);
    })();
  </script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../misc/SU_logo_small.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">SDA1</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Översikt</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Del1.html">
 <span class="menu-text">Del 1 - Dataanalys och regression</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../Del2.html">
 <span class="menu-text">Del 2 - Sannolikhetsmodeller och inferens</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../R.html">
 <span class="menu-text">R</span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Avsnitt på sidan</h2>
   
  <ul>
  <li><a href="#introduktion-och-viktig-förberedande-information" id="toc-introduktion-och-viktig-förberedande-information" class="nav-link active" data-scroll-target="#introduktion-och-viktig-förberedande-information">Introduktion och viktig förberedande information</a>
  <ul class="collapse">
  <li><a href="#fördelningar-i-r-r-p-d-och-q-funktionerna" id="toc-fördelningar-i-r-r-p-d-och-q-funktionerna" class="nav-link" data-scroll-target="#fördelningar-i-r-r-p-d-och-q-funktionerna">Fördelningar i R: r, p, d och q-funktionerna 😍</a></li>
  <li><a href="#rita-upp-sannolikhetsfördelningen-för-en-diskret-variabel" id="toc-rita-upp-sannolikhetsfördelningen-för-en-diskret-variabel" class="nav-link" data-scroll-target="#rita-upp-sannolikhetsfördelningen-för-en-diskret-variabel">Rita upp sannolikhetsfördelningen för en diskret variabel</a></li>
  <li><a href="#rita-upp-täthetsfunktionen-för-en-kontinuerlig-variabel" id="toc-rita-upp-täthetsfunktionen-för-en-kontinuerlig-variabel" class="nav-link" data-scroll-target="#rita-upp-täthetsfunktionen-för-en-kontinuerlig-variabel">Rita upp täthetsfunktionen för en kontinuerlig variabel</a></li>
  </ul></li>
  <li><a href="#räkna-med-sannolikhetsfördelningar" id="toc-räkna-med-sannolikhetsfördelningar" class="nav-link" data-scroll-target="#räkna-med-sannolikhetsfördelningar">1. Räkna med sannolikhetsfördelningar</a></li>
  <li><a href="#simulera-slumpvariabler" id="toc-simulera-slumpvariabler" class="nav-link" data-scroll-target="#simulera-slumpvariabler">2. Simulera slumpvariabler</a></li>
  <li><a href="#simulering-för-att-beräkna-nya-fördelningar" id="toc-simulering-för-att-beräkna-nya-fördelningar" class="nav-link" data-scroll-target="#simulering-för-att-beräkna-nya-fördelningar">3. Simulering för att beräkna nya fördelningar</a></li>
  <li><a href="#analys-av-antalet-besök-till-webbsida" id="toc-analys-av-antalet-besök-till-webbsida" class="nav-link" data-scroll-target="#analys-av-antalet-besök-till-webbsida">4. Analys av antalet besök till webbsida</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistik och dataanalys I, 15 hp</h1>
<p class="subtitle lead">Datorlaboration 5 - Simulering</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading"> </div>
    <div class="quarto-title-meta-contents">
             <p>Mattias Villani </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Publicerad</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 3, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduktion-och-viktig-förberedande-information" class="level2">
<h2 class="anchored" data-anchor-id="introduktion-och-viktig-förberedande-information">Introduktion och viktig förberedande information</h2>
<blockquote class="blockquote">
<p>I den här datorlabben kommer vi att arbeta med fördelningar i R, bland annat lära oss göra sannolikhetsberäkningar och simulera från olika fördelningar, dvs dra slumptal från fördelningar.</p>
</blockquote>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Installera paket
</div>
</div>
<div class="callout-body-container callout-body">
<p>Den här labben förutsätter inga installerade paket.</p>
</div>
</div>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Skapa mapp för labben
</div>
</div>
<div class="callout-body-container callout-body">
<p>Skapa en mapp <code>Lab5</code> i din kursmapp SDA1. Ladda ner Quarto-filen för denna lab genom att högerklicka <a href="https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab5/DatorLab5.qmd">här</a> och välj ‘Spara länk’ eller något likande från menyn som dyker upp. Spara filen i din <code>Lab5</code> mapp. Öppna Quarto-filen i RStudio och fortsätt med denna laboration direkt i Quarto-dokumentet, där du också fyller i svaren på dina laborationsövningar.</p>
</div>
</div>
<section id="fördelningar-i-r-r-p-d-och-q-funktionerna" class="level3">
<h3 class="anchored" data-anchor-id="fördelningar-i-r-r-p-d-och-q-funktionerna">Fördelningar i R: r, p, d och q-funktionerna 😍</h3>
<p>R har en massa statistiska fördelningar inbyggda från start, och ytterligare många, många mer i olika R-paket. För varje fördelning finns det fyra typer av funktioner:</p>
<ul>
<li><p><strong>r</strong>-funktionen som genererar slumptal från fördelningen, t ex <code>rnorm(n = 5, mean = 2, sd = 3)</code> genererar 5 slumptal från normalfördelningen <span class="math inline">\(X\sim N(2,3)\)</span>. Argumentet <code>sd</code> betyder standard deviation, dvs standardavvikelse. Tio slumptal från Poissonfördelningen <span class="math inline">\(\mathrm{Pois}(\lambda = 2)\)</span> får man med <code>rpois(n = 10, lambda = 2)</code> osv. r-funktionen har fått sitt namn från <strong>r</strong>andom.</p></li>
<li><p><strong>p</strong>-funktionen som beräknar sannolikheten att slumpvariabeln är mindre än ett visst tal, dvs <span class="math inline">\(P(X\leq x)\)</span> för något <span class="math inline">\(x\)</span>. p-funktionen har fått sitt namn från engelskans <strong>p</strong>robability.<br>
<code>pnorm(q = 1, mean = 2, sd = 3)</code> beräknar sannolikheten att <span class="math inline">\(X\sim N(2,3)\)</span> är mindre än 1.</p></li>
<li><p><strong>d</strong>-funktionen som för en diskret variabel <span class="math inline">\(X\)</span> beräknar sannolikheten <span class="math inline">\(P(X=x)\)</span>. För en kontinuerlig variabel beräknar d-funktionen täthetsfunktionen <span class="math inline">\(f(x)\)</span> i en given punkt <span class="math inline">\(x\)</span>. Det är från det kontinuerliga fallet som d-funktionen fått sitt namn, d som i <strong>d</strong>ensity. Kommandot <code>dnorm(x = 0, mean = 2, sd = 3)</code> beräknar täthetsfunktionens värde i punkten <span class="math inline">\(x=0\)</span>, dvs <span class="math inline">\(f(0)\)</span> för en <span class="math inline">\(X\sim N(2,3)\)</span> variabel.</p></li>
<li><p><strong>q</strong>-funktionen beräknar <span class="math inline">\(p\)</span>-kvantilen för en fördelning, dvs det värde <span class="math inline">\(x\)</span> där <span class="math inline">\(P(X \leq x)=p\)</span>. Vi kan t ex beräkna 25% eller 0.25-kvantilen för en normalfördelad variabel <span class="math inline">\(X\sim N (2,3)\)</span> med kommandot <code>qnorm(p = 0.25, mean = 2, sd = 3)</code>.</p>
<div class="cell">
<details>
<summary>Visa mig koden!</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>m <span class="ot">=</span> <span class="dv">2</span>       <span class="co"># mean for the normal distribution</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>s <span class="ot">=</span> <span class="dv">3</span>       <span class="co"># standard deviation for the normal distribution</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> <span class="sc">-</span><span class="dv">1</span>      <span class="co"># point where the density is evaluated</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>x_grid <span class="ot">=</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="fl">0.1</span>) <span class="co"># a vector of x-values for which we evaluate the density f(x)</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>x_sample <span class="ot">=</span> <span class="fu">rnorm</span>(<span class="at">n =</span> <span class="dv">1000</span>, <span class="at">mean =</span> m, <span class="at">sd =</span> s)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>dens_norm <span class="ot">=</span> <span class="fu">dnorm</span>(x_grid, <span class="at">mean =</span> m, <span class="at">sd =</span> s)  <span class="co"># density (x) for all values in vector xgrid</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>quantile10 <span class="ot">=</span> <span class="fu">qnorm</span>(<span class="fl">0.1</span>, <span class="at">mean =</span> m, <span class="at">sd =</span> s)    <span class="co"># 10% percentile</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting - a lot of code because I want pretty colors and legends. Sorry.</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(x_sample, <span class="at">breaks =</span> <span class="dv">50</span>, <span class="at">freq =</span> F, <span class="at">main =</span> <span class="st">"X ~ N(2,3²)"</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.15</span>), </span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,<span class="dv">10</span>), <span class="at">xlab =</span> <span class="st">"x"</span>, <span class="at">ylab =</span> <span class="st">"f(x)"</span>, <span class="at">col =</span> <span class="st">"cornflowerblue"</span>) <span class="co"># freq = F gives us proportions</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x_grid, dens_norm, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"orange"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>density_at_x <span class="ot">=</span> <span class="fu">dnorm</span>(x, <span class="at">mean =</span> m, <span class="at">sd =</span> s)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(x, density_at_x)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> <span class="fu">c</span>(x,x), <span class="fu">c</span>(<span class="dv">0</span>,density_at_x), <span class="at">col =</span> <span class="st">"gray"</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">3</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">10</span>,x), <span class="fu">c</span>(density_at_x,density_at_x), <span class="at">col =</span> <span class="st">"gray"</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>x_lower <span class="ot">=</span> x_grid[x_grid <span class="sc">&lt;</span> quantile10]</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="at">x =</span> <span class="fu">c</span>(x_lower, <span class="fu">rev</span>(x_lower)), <span class="at">border =</span> <span class="cn">NA</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">y =</span> <span class="fu">c</span>(<span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(x_lower)), <span class="fu">rev</span>(<span class="fu">dnorm</span>(x_lower, <span class="at">mean =</span> m, <span class="at">sd =</span> s))), </span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">rgb</span>(<span class="dv">1</span>,<span class="fl">0.8431373</span>,<span class="dv">0</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">inset=</span>.<span class="dv">01</span>, </span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend=</span><span class="fu">c</span>(<span class="st">"histogram data"</span>, <span class="st">"density function"</span>, <span class="st">"density evaluation"</span>, <span class="st">"P(X&lt;=-1)"</span>),</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="fu">c</span>(<span class="st">"cornflowerblue"</span>, <span class="st">"orange"</span>, <span class="st">"gray"</span>), </span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="dv">1</span>, <span class="dv">3</span>, <span class="cn">NA</span>), </span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd =</span> <span class="fu">c</span>(<span class="cn">NA</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="cn">NA</span>), </span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="fu">c</span>(<span class="st">"cornflowerblue"</span>, <span class="cn">NA</span>, <span class="cn">NA</span>, <span class="fu">rgb</span>(<span class="dv">1</span>,<span class="fl">0.8431373</span>,<span class="dv">0</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>)), </span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">border =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">cex=</span><span class="dv">1</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="DatorLab5_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid" width="672"></p>
</div>
</div></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>dnorm to compute density at -1: f(x) = 0.0806569081730478</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>pnorm to compute prob that X is lower than -1: P(X&lt;=x) = 0.158655253931457</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>qnorm to compute 10% quantile of X as  -1.8446546966338</code></pre>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Glöm inte Rs hjälp!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Skriv t ex <code>?rnorm</code> i Console för att se hjälpfilen för normalfördelningen.</p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Observera
</div>
</div>
<div class="callout-body-container callout-body">
<p>Jag har skrivit ut namnen på alla funktionsargumenten ovan, t ex <code>n=5</code>, <code>mean = 2</code> och <code>sd = 3</code> i <code>rnorm(n = 5, mean = 2, sd = 3)</code>. Det hade dock gått lika bra att skriva <code>rnorm(5, 2, 3)</code>, då förstår R att jag menar <code>n=5</code>, <code>mean = 2</code> och <code>sd = 3</code> . Det fungerar dock bara om man använder exakt den <strong>ordning</strong> på argumenten som man ser när man skriver <code>?rnorm</code>. Annars kan R inte veta vilka argument som ska matchas mot vilka siffror. Om man skriver ut argumentens namn så kan man ha vilken ordning som helst, t ex <code>rnorm(mean = 2, sd = 3, n = 5)</code>.</p>
</div>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Vektorisera mera
</div>
</div>
<div class="callout-body-container callout-body">
<p>Kommandot <code>dnorm(0, mean = 0, sd = 1)</code> räknar ut täthetsfunktionens värde i punkten <code>x=0</code> för en standard normalfördelning. Om man vill räkna ut tätheten i flera punkter? Ett sätt är att använda en <code>for</code>-loop som upprepar <code>dnorm(x, mean = 0, sd = 1)</code> för olika x-värden (se Lab1). Men det finns ett enklare sätt! Många av Rs funktioner är <strong>vektoriserade</strong>. Det betyder att du kan räkna ut funktionen för <em>alla</em> värden i en vektor ‘på en gång’. 😍<br>
Så här beräknar man t ex täthetsfunktionen för tre olika x-värden -1, 0, och 1:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2419707 0.3989423 0.2419707</code></pre>
</div>
</div>
<p>Ok, snyggt, men om man vill ha <em>olika</em> väntevärden för var och ett av x-värdena, då? Yep, funkar:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>), <span class="at">mean =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.5</span>, <span class="dv">3</span>), <span class="at">sd =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.24197072 0.35206533 0.05399097</code></pre>
</div>
</div>
</div>
</div>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Normalfördelning med varians eller standardavvikelse?
</div>
</div>
<div class="callout-body-container callout-body">
<p>I funktionen <code>rnorm()</code> anger man fördelningens spridning som en standardavvikelse med argumentet <code>sd</code>. Det motsvarar att man skriver <span class="math inline">\(N(\mu,\sigma)\)</span> för en normalfördelning i matematisk/symbolisk notation. Många böcker skriver dock normalfördelningen med <strong>variansen</strong> som andra argument i den symboliska beskrivningen: <span class="math inline">\(N(\mu,\sigma^2)\)</span>. Man får helt enkelt se upp och kontrollera om en normalfördelning skrivs med en standardavvikelse eller varians. I formelsamlingen och på tentan har jag kommer jag skriva <span class="math inline">\(N(\mu,\sigma)\)</span>, som boken gör.</p>
</div>
</div>
</section>
<section id="rita-upp-sannolikhetsfördelningen-för-en-diskret-variabel" class="level3">
<h3 class="anchored" data-anchor-id="rita-upp-sannolikhetsfördelningen-för-en-diskret-variabel">Rita upp sannolikhetsfördelningen för en diskret variabel</h3>
<p>Vi ska nu försöka göra ett stapeldiagram för sannolikhetsfördelningen för en binomialfördelad variabel med parametrarna <span class="math inline">\(n=10\)</span> och <span class="math inline">\(p=0.4\)</span>, dvs för slumpvariabeln <span class="math inline">\(X\sim \mathrm{Binom}(n,p)\)</span>. Vi har ju just sett att vi kan beräkna sannolikheterna <span class="math inline">\(P(X=x)\)</span> för en massa olika <span class="math inline">\(x\)</span>-värden genom vektorisering, så låt oss börja där:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="fl">0.4</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>xvalues <span class="ot">=</span> <span class="fu">seq</span>(<span class="dv">0</span>,n) <span class="co"># en vektor med alla möjliga utfall på X, dvs 0,1,2,...,n</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">=</span> <span class="fu">dbinom</span>(<span class="at">x =</span> xvalues, <span class="at">size =</span> n, <span class="at">prob =</span> p) <span class="co"># vektoriserat </span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>probs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 0.0060466176 0.0403107840 0.1209323520 0.2149908480 0.2508226560
 [6] 0.2006581248 0.1114767360 0.0424673280 0.0106168320 0.0015728640
[11] 0.0001048576</code></pre>
</div>
</div>
<p>Notera hur jag först skapade en vektor med alla x-värden (<code>xvalues</code>) mellan <span class="math inline">\(0\)</span> och <span class="math inline">\(n=10\)</span> (vilket ju är alla möjliga x-värden för en <span class="math inline">\(\mathrm{Bin}(10,p)\)</span>-fördelad variabel). Den vektorn matade jag sen in i <code>dbinom()</code> funktionen för att få sannolikheten <span class="math inline">\(P(X=x)\)</span> för <em>varje</em> x-värde. Vi ser att sannolikheten för <span class="math inline">\(x=0\)</span> är väldigt låg <span class="math inline">\(P(X=0)=0.0060466176\)</span>. Den sannolikheten är lätt att räkna för hand som kontroll: det enda sätt vi kan få 0 lyckade försök i 10 Bernoulliförsök är om vi misslyckas (vars sannolikhet är <span class="math inline">\(q=1-p=1-0.4=0.6\)</span>) på alla 10 försök: <span class="math inline">\(0.6^{10}=0.006046618\)</span>. Yes, checks out.</p>
<p>Koden nedan gör nu ett stapeldiagram över sannolikhetsfördelningen. Notera att vi måste använda <code>names()</code> funktionen för sätta ett “namn” på varje sannolikhet (dvs det x-värde som sannolikheten hör ihop med) för att vi ska få <span class="math inline">\(x\)</span>-värdena utskrivna på <span class="math inline">\(x\)</span>-axeln.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(probs) <span class="ot">&lt;-</span> xvalues</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(probs, <span class="at">col =</span> <span class="st">"cornflowerblue"</span>, <span class="at">ylab =</span> <span class="st">"P(X=x)"</span>, <span class="at">xlab =</span> <span class="st">"x"</span>, <span class="at">main =</span> <span class="st">"X ~ Binom(10,0.4)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DatorLab5_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Hur gör man om slumpvariabeln kan anta ett oändligt antal värden, som t ex Poissonfördelningen där <span class="math inline">\(x=0,1,2,….\)</span> utan övre gräns? Lösningen är att låta vektorn med x-värden innehålla alla x-värden där sannolikheten <span class="math inline">\(P(X=x)\)</span> är tillräckligt stor för att spela roll i figuren. Här kan prova sig fram, dvs öka på antalet x-värden tills sannolikheten för större x-värden är nära noll. Så här kan vi t ex göra ett stapeldiagram över sannolikhetsfördelningen för en <span class="math inline">\(\mathrm{Pois}(\lambda = 2)\)</span> variabel:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>xvalues <span class="ot">=</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">=</span> <span class="fu">dpois</span>(<span class="at">x =</span> xvalues, <span class="at">lambda =</span> <span class="dv">2</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(probs) <span class="ot">&lt;-</span> xvalues</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(probs, <span class="at">col =</span> <span class="st">"orange"</span>, <span class="at">xlab  =</span> <span class="st">"x"</span>, <span class="at">ylab =</span> <span class="st">"P(X=x)"</span>, <span class="at">main =</span> <span class="st">"Poisson med lite för få x-värden"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DatorLab5_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Som du ser var jag lite för snål med antal x-värden, det verkar som om x-värden större än 5 borde ha varit med i plotten eftersom sannolikheten för x=5 är inte riktigt nära noll. Låt oss prova med värden från 0 till 10:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>xvalues <span class="ot">=</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">10</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">=</span> <span class="fu">dpois</span>(<span class="at">x =</span> xvalues, <span class="at">lambda =</span> <span class="dv">2</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(probs) <span class="ot">&lt;-</span> xvalues</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(probs, <span class="at">col =</span> <span class="st">"yellow"</span>, <span class="at">xlab  =</span> <span class="st">"x"</span>, <span class="at">ylab =</span> <span class="st">"P(X=x)"</span>, <span class="at">main =</span> <span class="st">"Poisson med lagom många x-värden"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DatorLab5_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="rita-upp-täthetsfunktionen-för-en-kontinuerlig-variabel" class="level3">
<h3 class="anchored" data-anchor-id="rita-upp-täthetsfunktionen-för-en-kontinuerlig-variabel">Rita upp täthetsfunktionen för en kontinuerlig variabel</h3>
<p>Hur kan man rita upp sannolikheterna för en kontinuerlig variabel? Kontinuerliga variabler antar ju alla värden, även decimaltal, så här måste vi göra lite annorlunda. En kontinuerlig variabel har ju också sannolikhet noll för alla <span class="math inline">\(x\)</span>: <span class="math inline">\(P(X=x)=0\)</span>. Vi använder oss därför av täthetsfunktionen <span class="math inline">\(f(x)\)</span>, där arean under täthetsfunktionen mellan två x-värden <span class="math inline">\(a\)</span> och <span class="math inline">\(b\)</span> är sannolikheten <span class="math inline">\(P(a \leq X \leq b)\)</span>. Den s k d-funktionen (t ex <code>dnorm</code> för normalfördelning) ger tätheten för en kontinuerlig variabel. För att plotta upp en täthetsfunktion:</p>
<ul>
<li><p>skapa en vektor med en massa x-värden med ganska litet avstånd mellan värdena</p></li>
<li><p>beräkna d-funktionen för vektorn med x-värden</p></li>
<li><p>plotta täthetsfunktionen som en kurva med kommandot <code>plot()</code> eller <code>lines()</code> (används om det inte redan finns något uppritat i grafen).</p></li>
</ul>
<p>Här plottar vi täthetsfunktionen för en standard normalfördelningen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>xvalues <span class="ot">=</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">3</span>, <span class="dv">3</span>, <span class="at">by =</span> <span class="fl">0.01</span>) <span class="co"># by=0.01 talar om att vi vill ha avstånd 0.01 mellan värdena.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>density_values <span class="ot">=</span> <span class="fu">dnorm</span>(xvalues, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">1</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(xvalues, density_values, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">xlab =</span> <span class="st">"x"</span>, <span class="at">ylab =</span> <span class="st">"density"</span>, <span class="at">main =</span> <span class="st">"N(0,1)"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>) <span class="co"># lwd är line width, dvs tjocklek på linje.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="DatorLab5_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>I det här fallet var det ganska lätt att välja start- och slutpunkt för x-värdena: vi vet ju från 68-95-99.7 regeln att 99.7% av sannolikhetsmassan ligger mellan -3 och 3 för standard normalfördelning. I andra fall kan det vara svårare att bestämma lämpliga x-värden och man får prova sig fram (om man har en q-funktion, dvs kvantilfunktion, för fördelningen kan man använda den för att beräkna lämpliga start- och slutvärden på x). Hur väljer man avståndet mellan olika x-värden (dvs <code>by = 0.01</code> i min kod)? Det brukar spela mindre roll. Väljer man för stora avstånd blir kurvan hackig. Väljer man verkligt små avstånd blir det många olika x-värden och det kan ta tid för R beräkna alla täthetsvärden.</p>
</section>
</section>
<section id="räkna-med-sannolikhetsfördelningar" class="level2">
<h2 class="anchored" data-anchor-id="räkna-med-sannolikhetsfördelningar">1. Räkna med sannolikhetsfördelningar</h2>
<section id="uppgift-1.1" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-1.1">💪 Uppgift 1.1</h4>
<p>Låt <span class="math inline">\(X\sim \mathrm{Pois}(\lambda)\)</span> med <span class="math inline">\(\lambda = 2\)</span>. Beräkna <span class="math inline">\(P(X=2)\)</span> och <span class="math inline">\(P(X\leq 3)\)</span>. Hint: <code>?ppois</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="uppgift-1.2" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-1.2">💪 Uppgift 1.2</h4>
<p>I valet 2022 fick Liberalerna 4.61% av rösterna. I en undersökning bland totalt 1046 personser angav 30 personer att de skulle rösta på Liberalerna om det var val idag. Kan det vara så att Liberalernas röstningsandel är (ungefär) oförändrad på 4.61%, eller tyder den nya undersökningen på något annat? Undersök detta genom att rita upp ett stapeldiagram över sannolikhetsfördelningen <span class="math inline">\(P(X=x)\)</span> för <span class="math inline">\(X \sim \mathrm{Binom}\operatorname{}(n= 1046, p = 0.0461)\)</span> för x-värdena <code>xvalues = 0:100</code>. Är resultatet från valundersökningen ett sannolikt utfall? Om inte, vilket slutsats drar du, genom att titta i stapeldiagramet, om Liberalernas faktiska väljarandel?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="uppgift-1.3" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-1.3">💪 Uppgift 1.3</h4>
<p>Beräkna <span class="math inline">\(P(X \leq 30)\)</span> för <span class="math inline">\(X \sim \mathrm{Binom}(n= 1046, p = 0.0461)\)</span> genom att använda binomialfördelningen. Jämför svaret med samma sannolikhet från en normalapproximation (se F15):</p>
<p><span class="math display">\[
X\sim \mathrm{Binom}(n,p) \text{ approximeras med } X\sim \mathrm{N}\Big(\mu=np, \sigma = \sqrt{n p (1-p)}\Big)
\]</span></p>
<p>Observera att jag skrivit normalfördelningen med <em>standardavvikelse</em> som andra argument här. Precis som R gör.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="simulera-slumpvariabler" class="level2">
<h2 class="anchored" data-anchor-id="simulera-slumpvariabler">2. Simulera slumpvariabler</h2>
<section id="uppgift-2.1" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-2.1">💪 Uppgift 2.1</h4>
<p>Simulera nu 1000 slumptal från Poissonfördelningen <span class="math inline">\(\mathrm{Pois}(\lambda)\)</span> med <span class="math inline">\(\lambda = 2\)</span> och spara i variabeln (vektorn) <code>x</code>. Beräkna medelvärdet (<code>mean(x)</code>) och standardavvikelsen (<code>sd(x)</code>) för slumptalen. Stämmer de värdena ungefär med vad vi kan förvänta oss? [hint: Poissonfördelningens teoretiska väntevärde]. Simulera nu 10000 slumptal från samma fördelning och beräkna återigen medelvärdet. Vad tror du skulle hända om du fortsatte så här och simulerade fler och fler slumptal? (bortsett från att datorns minne skulle ta slut). [Hint: stora talens lag].</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="uppgift-2.2" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-2.2">💪 Uppgift 2.2</h4>
<p>Antag att du inte känner till funktionen <code>dpois</code> och att det matematiska uttrycket för Poissonsannolikheterna som ges i SDM boken är för skrämmande för dig. Kan du använda slumptalen i Uppgift 2.1 för att uppskatta sannolikheten <span class="math inline">\(P(X=3)\)</span>?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="uppgift-2.3" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-2.3">💪 Uppgift 2.3</h4>
<p>Simulera 1000 slumptal från exponentialfördelningen med parametern <code>rate = 2</code> (vilket är det som boken kallar <span class="math inline">\(\lambda\)</span>) och spara i en vektor x. Beräkna medelvärdet av slumptalen och verifiera att det är hyfsat nära det teoretiska väntevärdet för denna exponentialfördelning.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="uppgift-2.4" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-2.4">💪 Uppgift 2.4</h4>
<p>Rita ett histogram för slumptalen från förra uppgiften med argumentet <code>breaks = 40</code> (gör att du får ungefär 40 staplar i histogrammet). Plotta också den teoretiska täthetsfunktionen för <span class="math inline">\(\mathrm{Expon}(\lambda = 2)\)</span> i samma figur.</p>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Plottips
</div>
</div>
<div class="callout-body-container callout-body">
<p>Använd <code>lines()</code> när du plottar täthetsfunktionen, annars kommer histogrammet att skrivas över. Använd argumentet <code>freq = FALSE</code> i <code>hist()</code>-funktionen så du får andelen observationer i varje bin, och inte antalet. Annars kommer histogrammet och täthetsfunktionen inte att ha samma skala på y-axeln.</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="simulering-för-att-beräkna-nya-fördelningar" class="level2">
<h2 class="anchored" data-anchor-id="simulering-för-att-beräkna-nya-fördelningar">3. Simulering för att beräkna nya fördelningar</h2>
<p>En mycket trevlig egenskap med simulering är att det är väldigt enkelt att beräkna fördelningen för en <strong>funktion</strong> av slumpvariabler. Vi vet ju t ex att om <span class="math inline">\(X\sim \operatorname{N}(\mu,\sigma^2)\)</span> så är fördelningen för linjärkombinationen <span class="math inline">\(Y=c+aX\)</span> också normalfördelad: <span class="math inline">\(Y\sim \operatorname{N}(c+a\mu, a^2 \sigma ^2)\)</span>. Men det är långt ifrån alla fall där vi matematiskt kan bevisa sådana goa resultat. Med simulering kan vi få fram fördelningen för <em>alla</em> funktioner och även fördelningen för en summa av slumpvariabler, och mer. Den kan vi även göra om fördelningen för <span class="math inline">\(X\)</span> är något annat än normalfördelad. Låt oss testa direkt i en övning!</p>
<section id="uppgift-3.1" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-3.1">💪 Uppgift 3.1</h4>
<p>Din vän och du ska beställa hem mat. Ni har olika smak och du vill beställa från restaurang X, din vän vill beställa från restaurang Y. Ni vill såklart gärna äta maten samtidigt och lovar varandra att vänta med att äta tills båda fått maten. Låt <span class="math inline">\(X \sim \mathrm{Expon}(\lambda = 2)\)</span> vara väntetiden i timmar tills restaurang X levererar mat hem till dig, och <span class="math inline">\(Y \sim \mathrm{Expon}(\lambda = 4)\)</span> är väntetiden för restaurang Y. Antag att <span class="math inline">\(X\)</span> och <span class="math inline">\(Y\)</span> är oberoende slumpvariabler. Slumpvariabeln <span class="math inline">\(Z=60(X-Y)\)</span> mäter då hur många minuter du måste vänta på maten efter att din vän redan fått maten, dvs hur länge din artiga vän måste vänta innan hen kan börja äta. Om <span class="math inline">\(Z\)</span> är negativ har du alltså fått maten före din vän. Här ser man direkt att <span class="math inline">\(Z=60(X-Y)\)</span> inte kan vara exponentialfördelad, <span class="math inline">\(Z\)</span> kan ju vara negativ! Använd simulering för att simulera från fördelningen för <span class="math inline">\(Z\)</span> och rita upp ett histogram för att representera täthetsfunktionen (använd argumentet <code>freq = FALSE</code> för att få andelar inom varje bin). Använd simuleringen för att uppskatta sannolikheten att du får maten efter din vän. [Hint1: Prova att skriva <code>Z&gt;0</code> i Console. Hint2: R hanterar TRUE som 1 och FALSE som 0, så t ex <code>sum(c(TRUE, FALSE, TRUE))</code> blir 2 i R].</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="uppgift-3.2" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-3.2">💪 Uppgift 3.2</h4>
<p>Uppskatta variansen för <span class="math inline">\(Z\)</span> genom simulering. Verifiera att uppskattningen är hyfsat nära den teoretiska variansen för för <span class="math inline">\(Z\)</span>. [Hint: F14 gav oss formler för variansen av en summa och en differens av oberoende variabler och F16 har egenskaper för exponentialfördelade variabler, t ex deras varians.]</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="analys-av-antalet-besök-till-webbsida" class="level2">
<h2 class="anchored" data-anchor-id="analys-av-antalet-besök-till-webbsida">4. Analys av antalet besök till webbsida</h2>
<p>En webbsida registrerade när besökare besökte deras webbsida under ett dygn. Här är en grafisk illustration av antalet besök under dygnet, varje streck är ett besök vid en viss tidpunkt:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab5/website_times.svg" class="img-fluid figure-img"></p>
</figure>
</div>
<p>Antalet besök för var och ett av dygnets timmar var</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>visits_per_hour <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>,  <span class="dv">6</span>,  <span class="dv">0</span>,  <span class="dv">1</span>,  <span class="dv">0</span>,  <span class="dv">1</span>,  <span class="dv">0</span>,  <span class="dv">3</span>,  <span class="dv">0</span>,  <span class="dv">0</span>,  <span class="dv">0</span>,  <span class="dv">0</span>,  <span class="dv">2</span>,  <span class="dv">2</span>, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>                    <span class="dv">0</span>,  <span class="dv">1</span>,  <span class="dv">9</span>,  <span class="dv">1</span>,  <span class="dv">1</span>,  <span class="dv">0</span>,  <span class="dv">1</span>,  <span class="dv">0</span>,  <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Antag att <em>antalet besök per timme</em> kan modelleras som oberoende Poissonfördelade variabler med parameter <span class="math inline">\(\lambda\)</span>. Vi vill nu bestämma det bästa värdet på <span class="math inline">\(\lambda\)</span> genom att använda data. En vanlig <strong>skattning</strong> av <span class="math inline">\(\lambda\)</span> i en Poissonfördelning är medelvärdet <span class="math inline">\(\bar x\)</span> av data (det är t ex den skattning man får med den s k <strong>maximum likelihoodmetoden</strong>).</p>
<section id="uppgift-4.1" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-4.1">💪 Uppgift 4.1</h4>
<p>Skatta parametern <span class="math inline">\(\lambda\)</span> från variabeln <code>visits_per_hour</code> .</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="uppgift-4.2" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-4.2">💪 Uppgift 4.2</h4>
<p>Företaget som driver webbsidan vill veta sannolikheten att de får fler än 5 besökare under <strong>åtminstone någon</strong> av morgondagens 24 timmar. Använd din skattade Poissonmodell för att beräkna den sannolikheten. [hint: union och komplement].</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="uppgift-4.2-1" class="level4">
<h4 class="anchored" data-anchor-id="uppgift-4.2-1">💪 Uppgift 4.2</h4>
<p><br>
Undersök om Poissonfördelningen verkar anpassa dessa data bra. Du kan t ex undersöka om det teoretiska väntevärdet och variansen i den skattade Poissonmodellen ligger hyfsat nära medelvärdet och stickprovsvariansen i data. Du kan också kolla hur sannolikt det faktiskt är att observera 9 st besök under en timme (som vi ju ser i data mellan kl 17-18) i den skattade Poissonmodellen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your code here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.su.se/statistiska-institutionen/">Statistiska institutionen - Stockholms universitet</a>
  </li>  
</ul>
    </div>   
      <div class="nav-footer-center">
        <ul class="footer-items list-unstyled">
    <li class="nav-item">
 Använd vår kurs!
  </li>  
</ul>
      </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/StatisticsSU/SDA1">
      <i class="bi bi-github" role="img" aria-label="Quarto GitHub">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>



</body></html>