---
title: "Statistik och dataanalys I, 15 hp "
subtitle: "Datorlaboration 6 - Samplingf칬rdelningar, intervall och hypotesttest"
author: 
  - Mattias Villani
date: last-modified
format: 
  html:
    self-contained: true
toc: true
execute:
  error: false
language: 
  title-block-author-single: " "
toc-title-document: "Inneh친ll"
crossref-fig-title: "Figur"
theme: Superhero
title-block-banner-color: Primary
title-block-published: "Publicerad"
callout-warning-caption: "Varning"
callout-note-caption: "Observera"
callout-tip-caption: "Tips"
editor: visual
---

::: callout-warning
## Installera paket

Den h칛r labben f칬ruts칛tter att f칬ljande paket finns installerade:

-   `mosaic`

Paket kan installeras via kommandot `install.packages('packagename')`, d칛r `'packagename'` 칛r namnet p친 paketet, t.ex `'mosaic'`.
:::

## Introduktion

> I den h칛r datorlabben kommer vi att arbeta med f칬rdelningar i R, bland annat l칛ra oss simulera fr친n olika f칬rdelningar, dvs dra slumptal fr친n f칬rdelningar.

#### 游눩 Uppgift 0.1

Se till att paketen ovan 칛r installerade i RStudio innan du forts칛tter med resten.

#### 游눩 Uppgift 0.2

Skapa en mapp `Lab5` i din kursmapp SDA1. Ladda ner Quarto-filen f칬r denna lab genom att h칬gerklicka [h칛r](https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab6/DatorLab6.qmd) och v칛lj 'Spara l칛nk' eller n친got likande fr친n menyn som dyker upp. Spara filen i din nya `Lab5` mapp. 칐ppna Quarto-filen i RStudio och forts칛tt med denna laboration direkt i Quarto-dokumentet, d칛r du ocks친 fyller i svaren p친 dina laborations칬vningar.
