---
title: "Statistik och dataanalys I, 15 hp "
subtitle: "Datorlaboration 7 - Regression"
author: 
  - Mattias Villani
date: last-modified
format: 
  html:
    self-contained: true
toc: true
execute:
  error: false
language: 
  title-block-author-single: " "
toc-title-document: "Inneh친ll"
crossref-fig-title: "Figur"
theme: Superhero
title-block-banner-color: Primary
title-block-published: "Publicerad"
callout-warning-caption: "Varning"
callout-note-caption: "Observera"
callout-tip-caption: "Tips"
editor: visual
---

::: callout-warning
## Installera paket

Den h칛r labben f칬ruts칛tter att f칬ljande paket finns installerade:

-   `sda1`

sda1 칛r kursens egna R-paket och m친ste installeras fr친n GitHub. Det g칬rs genom att f칬rst installera paketet remotes och d칛refter installera kurspaketet:

```{r}
# install.packages("remotes") # avkommentera f칬rsta g친ngen
library(remotes)
#install_github("StatisticsSU/sda1paket")  # avkommentera f칬rsta g친ngen
library(sda1)

```
:::

## Introduktion

> I den h칛r datorlabben kommer vi att arbeta med f칬rdelningar i R, bland annat l칛ra oss simulera fr친n olika f칬rdelningar, dvs dra slumptal fr친n f칬rdelningar.

#### 游눩 Uppgift 0.1

Se till att paketen ovan 칛r installerade i RStudio innan du forts칛tter med resten.

#### 游눩 Uppgift 0.2

Skapa en mapp `Lab5` i din kursmapp SDA1. Ladda ner Quarto-filen f칬r denna lab genom att h칬gerklicka [h칛r](https://github.com/StatisticsSU/SDA1/raw/main/datorlab/lab7/DatorLab7.qmd) och v칛lj 'Spara l칛nk' eller n친got likande fr친n menyn som dyker upp. Spara filen i din nya `Lab5` mapp. 칐ppna Quarto-filen i RStudio och forts칛tt med denna laboration direkt i Quarto-dokumentet, d칛r du ocks친 fyller i svaren p친 dina laborations칬vningar.

## Z. Estimera model

**Enkel regression**

Estimera p친 data

Tolka utskrift, g칬r test.

Prediktion

Prediktionsintervall med reg_predict

**Multipel**

Samma som ovan, men inte grafisk prediktionsintervall, bara med lm.predict och interval.

## Y. Simulera samplingf칬rdelning - enkel regression

-   Simulera enkel regressionsmodell f칬r hand. Ta fram samplingf칬rdelning f칬r b_1 genom simulering. Unders칬k v칛ntev칛rdesriktighet. J칛mf칬r simulerad f칬rdelning med teoretiska samplingf칬rdelningen.
-   L친t X:n vara korrelerade mer och mer korrelerade. Vad h칛nder med standardfelen? Varf칬r?

## X. Omitted variable bias

#### 游눩 Uppgift X.1

-   Simulera regression med tv친 kovariater med reg_simulate i sda1 paketet. Okorrelerade x. Skatta regression med bara x_1. Unders칬k unbiasedness.

-   Simulera regression med tv친 kovariater med reg_simulate i sda1 paketet. korrelerade x. Skatta regression med bara x_1. Unders칬k unbiasedness.
